### ISSUE TITLE
Elematilius ore everywhere 

### ISSUE THREAD

**Issue by Reikona** [Dalarion/Croparia#16]
Good afternoon.
I am having the following issue on Minecraft 1.18.2, Forge version 40.1.52.
(Also installed mod Biomes O'Plenty)

When generating a world, Elematilius ore appears instead of regular stone. It lies in a layer everywhere where an ordinary stone should be.

<img src="https://i.ibb.co/sRPPtGt/23-06-2022-064856.jpg" alt="23-06-2022-064856" border="0">
<img src="https://i.ibb.co/z2bQBD9/23-06-2022-064841.jpg" alt="23-06-2022-064841" border="0">

**Comment by Dalarion** [comment]
There is an error with the configs, you have to play with them. Sorry :/
