### ISSUE TITLE
Beta 4 Fabric: No seeds are harvestable. 

### ISSUE THREAD

**Issue by itsdinkd** [Dalarion/Croparia#2]
EDIT: Okay. The only way they are "Harvestable" is if you destroy the crop itself, which gives the fruit, and the seed. However, this means you have to **replant** the seed. 

Still, You cannot use fruit.... which means you can't really do anything with this mod other than make gear.

**Comment by Dalarion** [comment]
you have to use the knives to auto-replant the crops. I will check for the fruits

**Comment by Dalarion** [comment]
Everything is fine with the fruits, you juste have to place them in a crafting grid (inventory or crafting table)
