### ISSUE TITLE
To inform!

### ISSUE THREAD

**Issue by Rogenar** [Dalarion/Croparia#25]
![sdsd](https://user-images.githubusercontent.com/122460325/217540479-52f0fe04-54b1-45e8-8caf-194cebec3602.png)
How is Croparia obtained?

**Comment by Moeppelchen** [comment]
### T1
![image](https://user-images.githubusercontent.com/6907608/217880250-323217df-b933-4b27-a4ba-a7c500a05354.png)
### T2
![image](https://user-images.githubusercontent.com/6907608/217880416-c9f81650-5ce0-4834-9f82-09f14b846cf3.png)
### T3
![image](https://user-images.githubusercontent.com/6907608/217880496-077e07ca-bd9c-4cb7-a5ec-9cd939a1dd91.png)
### T4
![image](https://user-images.githubusercontent.com/6907608/217880550-1edff3d2-f4ce-4a57-ba07-e40f87cca01d.png)
### T5
![image](https://user-images.githubusercontent.com/6907608/217880604-3ef6f75b-e541-4b1a-bec9-f2bba7347eb8.png)
### T6
![image](https://user-images.githubusercontent.com/6907608/217880686-18d6b513-7e08-4860-886c-08c98a62b57b.png)
### T7
![image](https://user-images.githubusercontent.com/6907608/217880732-ef499cab-343b-4212-b99e-3d4c3eb05ff2.png)

**Comment by Rogenar** [comment]
I don't see these recipes. I'm playing fabric version 1.19.3.

**Comment by Dalarion** [comment]
Hum... how to say that... 
Did I forget to add the recipe in Croparia 4.1.0 ? Yes ! Did I just upload an update ? Yes I did !

**Comment by Dinocraft1515YT** [comment]
How to get "insulated copper wire"?
