### ISSUE TITLE
Invalid Loottables

### ISSUE THREAD

**Issue by LordDeatHunter** [Dalarion/Croparia#3]
1.17.1 - Fabric Beta 3
A lot of the loot tables have invalid block ids.
![image](https://user-images.githubusercontent.com/26803198/141644511-df83c793-6261-4c25-bdbe-c9d594d43d7d.png)
I couldn't find a Fabric repo, so I can't make a PR.

**Comment by Dalarion** [comment]
I think it has been fixed with the beta 4
