### ISSUE TITLE
Fabric SSP 1.20.4 Croparia 4.5: Recipes for crafting fruits to items are all missing

### ISSUE THREAD

**Issue by Knito58** [Dalarion/Croparia#30]
Fruits can only be done into the composter. No yields possible from farming other than standard crops like wheat and potatoes.

**Comment by MUYUTwilighter** [comment]
take a fruit on your hand and right click on a block, the fruit will convert to the corresponding resource items.

**Comment by Knito58** [comment]
Thank you.
