### ISSUE TITLE
[FABRIC-Croparia-1.20.1-4.5.1]Error in Star Platinum(Mythic Metal) Seeds

### ISSUE THREAD

**Issue by LiuH-Asye** [Dalarion/Croparia#33]
mythicmetals-0.19.3+1.20.1
![image](https://github.com/Dalarion/Croparia/assets/58126324/6e70a643-f8fb-4e41-a3f8-29dda5f6c94e)

**Comment by LiuH-Asye** [comment]
It is now called star_platinum in Mythic Metal, not star_platinum_ingots

**Comment by Dalarion** [comment]
Thank you.
Fixed in 4.5.2.
