### ISSUE TITLE
[FABRIC-Croparia-1.20.1-4.5.1]Can't start the game with Stemaria

### ISSUE THREAD

**Issue by LiuH-Asye** [Dalarion/Croparia#34]
FABRIC-Stemaria-2.1 and FABRIC-Stemaria-2.2 both can't

**Comment by Dalarion** [comment]
Can you send me the logs please ?

**Comment by LiuH-Asye** [comment]
Here you are
[debug.log](https://github.com/Dalarion/Croparia/files/15346988/debug.log)
[latest.log](https://github.com/Dalarion/Croparia/files/15346989/latest.log)

**Comment by LiuH-Asye** [comment]
maybe 4.3 is better (embarrassed)
