### ISSUE TITLE
[Fabric] Brewing and Infusion

### ISSUE THREAD

**Issue by cryxli** [Dalarion/Croparia#8]
### Version

- [[FABRIC] Croparia-3.8 MC 1.18.1](https://www.curseforge.com/minecraft/mc-mods/croparia/files/3637962)
- [[1.18.1] Fabric API 0.46.4+1.18](https://www.curseforge.com/minecraft/mc-mods/fabric-api/files/3634318)
- Minecraft 1.18.1

### Observation

- Elematilius cannot be placed in a brewing stand to create Elematilius Potion from water bottles.
- Forthermore, Elematilius cannot be dropped into a cauldron filled with water to turn it into Elematilius fluid.

### Suggestion

- I didn't check the source. But it looks like the brewing recipes are missing.
- (Future considerations) Would it make sense to add a Getting Started section on top of the Curse page to make it easier for new players to obtain Elematilius Seeds... ATM it is "hidden" under the Infusor tab

**Comment by Dalarion** [comment]
Thank you a lot. You were right. It has been fixed in Croparia 3.8.1 and 3.8.2. I don't manage to add new breawing recipes with Fabric, but I have create another way : shapeless recipe with dragon breath+ elemental

**Comment by cryxli** [comment]
I've seen the recipe. Thanks for the confirmation.

This ticket is the result of comparing the CurseForge info page with the Fabric mod.  So far nothing game breaking, or even urgent. - On that note, feel free to close the issue.

Hope you'll find a way to have fabric behave the way you intended it to do.
